20-Sep-24 20:06:46 INFO: Start polling
20-Sep-24 20:06:46 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:07:01 INFO: Update id=769241887 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 20:07:45 INFO: Polling stopped
20-Sep-24 20:07:45 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:07:51 INFO: Start polling
20-Sep-24 20:07:51 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:07:53 INFO: Update id=769241888 is handled. Duration 172 ms by bot id=7214056159
20-Sep-24 20:09:23 INFO: Polling stopped
20-Sep-24 20:09:23 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:09:48 INFO: Start polling
20-Sep-24 20:09:48 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:09:52 INFO: Update id=769241889 is handled. Duration 172 ms by bot id=7214056159
20-Sep-24 20:11:02 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:11:02 INFO: Polling stopped
20-Sep-24 20:11:29 INFO: Start polling
20-Sep-24 20:11:29 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:11:29 INFO: Update id=769241890 is handled. Duration 170 ms by bot id=7214056159
20-Sep-24 20:11:30 INFO: Update id=769241891 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 20:11:46 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:11:46 INFO: Polling stopped
20-Sep-24 20:11:51 INFO: Start polling
20-Sep-24 20:11:51 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:11:58 INFO: Update id=769241892 is handled. Duration 280 ms by bot id=7214056159
20-Sep-24 20:11:59 INFO: Update id=769241893 is handled. Duration 79 ms by bot id=7214056159
20-Sep-24 20:12:00 INFO: Update id=769241894 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 20:12:29 INFO: Update id=769241895 is handled. Duration 202 ms by bot id=7214056159
20-Sep-24 20:12:30 INFO: Update id=769241896 is handled. Duration 47 ms by bot id=7214056159
20-Sep-24 20:12:31 INFO: Update id=769241897 is handled. Duration 63 ms by bot id=7214056159
20-Sep-24 20:15:41 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:15:41 INFO: Polling stopped
20-Sep-24 20:15:46 INFO: Start polling
20-Sep-24 20:15:47 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:16:59 INFO: Update id=769241898 is handled. Duration 640 ms by bot id=7214056159
20-Sep-24 20:18:06 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:18:06 INFO: Polling stopped
20-Sep-24 20:18:11 INFO: Start polling
20-Sep-24 20:18:11 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:18:14 INFO: Update id=769241899 is handled. Duration 171 ms by bot id=7214056159
20-Sep-24 20:20:57 INFO: Update id=769241900 is handled. Duration 171 ms by bot id=7214056159
20-Sep-24 20:20:58 INFO: Update id=769241901 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 20:21:06 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:21:06 INFO: Polling stopped
20-Sep-24 20:21:11 INFO: Start polling
20-Sep-24 20:21:11 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:21:25 INFO: Update id=769241902 is handled. Duration 421 ms by bot id=7214056159
20-Sep-24 20:21:28 INFO: Update id=769241903 is handled. Duration 140 ms by bot id=7214056159
20-Sep-24 20:22:07 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:22:07 INFO: Polling stopped
20-Sep-24 20:22:12 INFO: Start polling
20-Sep-24 20:22:12 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:22:12 INFO: Update id=769241904 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 20:22:14 INFO: Update id=769241905 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 20:22:19 INFO: Update id=769241906 is handled. Duration 78 ms by bot id=7214056159
20-Sep-24 20:22:22 INFO: Update id=769241907 is handled. Duration 92 ms by bot id=7214056159
20-Sep-24 20:22:31 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:22:31 INFO: Polling stopped
20-Sep-24 20:22:41 INFO: Start polling
20-Sep-24 20:22:41 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:22:42 INFO: Update id=769241908 is handled. Duration 155 ms by bot id=7214056159
20-Sep-24 20:22:44 INFO: Update id=769241909 is handled. Duration 344 ms by bot id=7214056159
20-Sep-24 20:22:44 INFO: Update id=769241910 is not handled. Duration 47 ms by bot id=7214056159
20-Sep-24 20:22:44 ERROR: Cause exception while process update id=769241910 by bot id=7214056159
TelegramBadRequest: Telegram server says - Bad Request: message can't be edited
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\addsite.py", line 22, in add_site_2step
    await msg.edit_text("Чудово!", reply_markup = main_kb)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message can't be edited
20-Sep-24 20:22:58 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:22:58 INFO: Polling stopped
20-Sep-24 20:23:03 INFO: Start polling
20-Sep-24 20:23:03 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:23:06 INFO: Update id=769241911 is not handled. Duration 125 ms by bot id=7214056159
20-Sep-24 20:23:06 ERROR: Cause exception while process update id=769241911 by bot id=7214056159
TelegramBadRequest: Telegram server says - Bad Request: message can't be edited
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\addsite.py", line 22, in add_site_2step
    await msg.edit_text(text = "Чудово!", reply_markup = main_kb)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message can't be edited
20-Sep-24 20:23:07 INFO: Update id=769241912 is handled. Duration 78 ms by bot id=7214056159
20-Sep-24 20:23:09 INFO: Update id=769241913 is handled. Duration 63 ms by bot id=7214056159
20-Sep-24 20:23:10 INFO: Update id=769241914 is not handled. Duration 46 ms by bot id=7214056159
20-Sep-24 20:23:10 ERROR: Cause exception while process update id=769241914 by bot id=7214056159
TelegramBadRequest: Telegram server says - Bad Request: message can't be edited
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\addsite.py", line 22, in add_site_2step
    await msg.edit_text(text = "Чудово!", reply_markup = main_kb)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message can't be edited
20-Sep-24 20:23:25 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:23:25 INFO: Polling stopped
20-Sep-24 20:23:30 INFO: Start polling
20-Sep-24 20:23:30 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:23:31 INFO: Update id=769241915 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 20:28:52 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:28:52 INFO: Polling stopped
20-Sep-24 20:28:57 INFO: Start polling
20-Sep-24 20:28:57 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:29:20 INFO: Update id=769241916 is handled. Duration 280 ms by bot id=7214056159
20-Sep-24 20:29:23 INFO: Update id=769241917 is not handled. Duration 92 ms by bot id=7214056159
20-Sep-24 20:29:23 ERROR: Cause exception while process update id=769241917 by bot id=7214056159
TypeError: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\addsite.py", line 24, in add_site_2step
    await db.add_site(msg.from_user.id, msg.text)
TypeError: object NoneType can't be used in 'await' expression
20-Sep-24 20:31:24 INFO: Polling stopped
20-Sep-24 20:31:24 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:31:30 INFO: Start polling
20-Sep-24 20:31:30 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:31:34 INFO: Update id=769241918 is not handled. Duration 16 ms by bot id=7214056159
20-Sep-24 20:31:34 ERROR: Cause exception while process update id=769241918 by bot id=7214056159
ValueError: parameters are of unsupported type
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 11, in start_cmd
    db.create_user(msg.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\database.py", line 25, in create_user
    cur.execute("SELECT * FROM users WHERE uid=?", uid,)
ValueError: parameters are of unsupported type
20-Sep-24 20:31:41 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:31:41 INFO: Polling stopped
20-Sep-24 20:32:33 INFO: Start polling
20-Sep-24 20:32:33 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:32:37 INFO: Update id=769241919 is not handled. Duration 15 ms by bot id=7214056159
20-Sep-24 20:32:37 ERROR: Cause exception while process update id=769241919 by bot id=7214056159
ValueError: parameters are of unsupported type
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 11, in start_cmd
    db.create_user(msg.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\database.py", line 25, in create_user
    cur.execute("SELECT * FROM users WHERE uid=?", uid,)
ValueError: parameters are of unsupported type
20-Sep-24 20:33:29 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:33:29 INFO: Polling stopped
20-Sep-24 20:33:36 INFO: Start polling
20-Sep-24 20:33:36 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:33:37 INFO: Update id=769241920 is not handled. Duration 14 ms by bot id=7214056159
20-Sep-24 20:33:37 ERROR: Cause exception while process update id=769241920 by bot id=7214056159
ValueError: parameters are of unsupported type
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 11, in start_cmd
    db.create_user(msg.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\database.py", line 26, in create_user
    cur.execute("SELECT * FROM users WHERE uid=?", uid,)
ValueError: parameters are of unsupported type
20-Sep-24 20:33:44 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:33:44 INFO: Polling stopped
20-Sep-24 20:33:49 INFO: Start polling
20-Sep-24 20:33:49 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:33:50 INFO: Update id=769241921 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 20:33:50 ERROR: Cause exception while process update id=769241921 by bot id=7214056159
ValueError: parameters are of unsupported type
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 11, in start_cmd
    db.create_user(msg.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\database.py", line 27, in create_user
    cur.execute("SELECT * FROM users WHERE uid=?", uid,)
ValueError: parameters are of unsupported type
20-Sep-24 20:34:44 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:34:44 INFO: Polling stopped
20-Sep-24 20:34:48 INFO: Start polling
20-Sep-24 20:34:48 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:34:50 INFO: Update id=769241922 is handled. Duration 155 ms by bot id=7214056159
20-Sep-24 20:34:57 INFO: Update id=769241923 is handled. Duration 63 ms by bot id=7214056159
20-Sep-24 20:43:27 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:43:27 INFO: Polling stopped
20-Sep-24 20:43:39 INFO: Start polling
20-Sep-24 20:43:39 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:43:48 INFO: Update id=769241924 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 20:44:05 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:44:05 INFO: Polling stopped
20-Sep-24 20:44:11 INFO: Start polling
20-Sep-24 20:44:11 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:44:11 INFO: Update id=769241925 is handled. Duration 265 ms by bot id=7214056159
20-Sep-24 20:46:40 INFO: Polling stopped
20-Sep-24 20:46:40 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:46:45 INFO: Start polling
20-Sep-24 20:46:45 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:46:48 INFO: Update id=769241926 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 20:46:51 INFO: Update id=769241927 is not handled. Duration 92 ms by bot id=7214056159
20-Sep-24 20:46:51 ERROR: Cause exception while process update id=769241927 by bot id=7214056159
TypeError: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\addsite.py", line 24, in add_site_2step
    await db.add_site(msg.from_user.id, msg.text)
TypeError: object NoneType can't be used in 'await' expression
20-Sep-24 20:46:53 INFO: Update id=769241928 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 20:46:53 ERROR: Cause exception while process update id=769241928 by bot id=7214056159
OperationalError: no such column: websites
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\usersites.py", line 10, in mysites_callback
    sites = db.get_user_links(call.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\database.py", line 36, in get_user_links
    cur.execute("SELECT websites FROM sites WHERE uid = ?", (uid,))
sqlite3.OperationalError: no such column: websites
20-Sep-24 20:47:01 INFO: Polling stopped
20-Sep-24 20:47:01 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:47:06 INFO: Start polling
20-Sep-24 20:47:06 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:47:08 INFO: Update id=769241929 is handled. Duration 297 ms by bot id=7214056159
20-Sep-24 20:47:20 INFO: Polling stopped
20-Sep-24 20:47:20 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:47:24 INFO: Start polling
20-Sep-24 20:47:24 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:47:32 INFO: Update id=769241930 is handled. Duration 171 ms by bot id=7214056159
20-Sep-24 20:47:38 INFO: Polling stopped
20-Sep-24 20:47:38 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:47:43 INFO: Start polling
20-Sep-24 20:47:43 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:47:43 INFO: Update id=769241931 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 20:47:44 INFO: Update id=769241932 is handled. Duration 78 ms by bot id=7214056159
20-Sep-24 20:48:00 INFO: Update id=769241933 is handled. Duration 141 ms by bot id=7214056159
20-Sep-24 20:48:01 INFO: Update id=769241934 is handled. Duration 92 ms by bot id=7214056159
20-Sep-24 20:48:01 INFO: Update id=769241935 is not handled. Duration 109 ms by bot id=7214056159
20-Sep-24 20:48:01 ERROR: Cause exception while process update id=769241935 by bot id=7214056159
TypeError: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\addsite.py", line 24, in add_site_2step
    await db.add_site(msg.from_user.id, msg.text)
TypeError: object NoneType can't be used in 'await' expression
20-Sep-24 20:48:03 INFO: Update id=769241936 is handled. Duration 61 ms by bot id=7214056159
20-Sep-24 20:48:33 INFO: Polling stopped
20-Sep-24 20:48:33 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:48:37 INFO: Start polling
20-Sep-24 20:48:37 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 20:58:04 INFO: Polling stopped
20-Sep-24 20:58:04 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:00:37 INFO: Start polling
20-Sep-24 21:00:37 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:00:39 INFO: Polling stopped
20-Sep-24 21:00:39 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:16:19 INFO: Start polling
20-Sep-24 21:16:19 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:16:26 INFO: Update id=769241937 is handled. Duration 125 ms by bot id=7214056159
20-Sep-24 21:16:29 INFO: Update id=769241938 is not handled. Duration 1813 ms by bot id=7214056159
20-Sep-24 21:16:29 ERROR: Cause exception while process update id=769241938 by bot id=7214056159
TypeError: Bot.send_message() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 17, in sdsd
    await check(Bot)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 35, in check
    await bot.send_message(chat_id=user[0], text=text)
TypeError: Bot.send_message() missing 1 required positional argument: 'self'
20-Sep-24 21:17:35 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:17:35 INFO: Polling stopped
20-Sep-24 21:17:44 INFO: Start polling
20-Sep-24 21:17:44 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:17:46 INFO: Update id=769241939 is not handled. Duration 1297 ms by bot id=7214056159
20-Sep-24 21:17:46 ERROR: Cause exception while process update id=769241939 by bot id=7214056159
AttributeError: type object 'Bot' has no attribute 'bot'
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 17, in sdsd
    await check(Bot)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 35, in check
    await self.bot.send_message(chat_id=user[0], text=text)
AttributeError: type object 'Bot' has no attribute 'bot'
20-Sep-24 21:17:47 INFO: Polling stopped
20-Sep-24 21:17:47 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:18:02 INFO: Start polling
20-Sep-24 21:18:02 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:18:04 INFO: Update id=769241940 is not handled. Duration 1014 ms by bot id=7214056159
20-Sep-24 21:18:04 ERROR: Cause exception while process update id=769241940 by bot id=7214056159
TypeError: Bot.send_message() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 17, in sdsd
    await check(Bot)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 34, in check
    await bot.send_message(chat_id=user[0], text=text)
TypeError: Bot.send_message() missing 1 required positional argument: 'self'
20-Sep-24 21:18:06 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:18:06 INFO: Polling stopped
20-Sep-24 21:18:47 INFO: Start polling
20-Sep-24 21:18:47 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:18:51 INFO: Update id=769241942 is not handled. Duration 1594 ms by bot id=7214056159
20-Sep-24 21:18:51 ERROR: Cause exception while process update id=769241942 by bot id=7214056159
TypeError: Bot.send_message() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 17, in sdsd
    await check(Bot)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 34, in check
    await bot.send_message(chat_id=user[0], text=text)
TypeError: Bot.send_message() missing 1 required positional argument: 'self'
20-Sep-24 21:19:56 INFO: Polling stopped
20-Sep-24 21:19:56 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:20:00 INFO: Start polling
20-Sep-24 21:20:00 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:20:04 INFO: Update id=769241943 is handled. Duration 1969 ms by bot id=7214056159
20-Sep-24 21:21:06 INFO: Polling stopped
20-Sep-24 21:21:06 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:21:10 INFO: Start polling
20-Sep-24 21:21:10 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:21:15 INFO: Update id=769241944 is handled. Duration 2828 ms by bot id=7214056159
20-Sep-24 21:21:25 INFO: Update id=769241945 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 21:21:30 INFO: Update id=769241946 is handled. Duration 125 ms by bot id=7214056159
20-Sep-24 21:21:37 INFO: Update id=769241947 is handled. Duration 61 ms by bot id=7214056159
20-Sep-24 21:21:42 INFO: Update id=769241948 is handled. Duration 3047 ms by bot id=7214056159
20-Sep-24 21:22:13 INFO: Polling stopped
20-Sep-24 21:22:13 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:22:20 INFO: Start polling
20-Sep-24 21:22:20 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:22:24 INFO: Update id=769241949 is handled. Duration 2765 ms by bot id=7214056159
20-Sep-24 21:24:38 INFO: Polling stopped
20-Sep-24 21:24:38 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:24:43 INFO: Start polling
20-Sep-24 21:24:43 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:25:06 INFO: Polling stopped
20-Sep-24 21:25:06 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:25:11 INFO: Start polling
20-Sep-24 21:25:11 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:26:30 INFO: Polling stopped
20-Sep-24 21:26:30 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:26:34 INFO: Start polling
20-Sep-24 21:26:34 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:27:06 INFO: Polling stopped
20-Sep-24 21:27:06 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:27:11 INFO: Start polling
20-Sep-24 21:27:11 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:27:16 INFO: Polling stopped
20-Sep-24 21:27:16 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:27:28 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 21:27:28 INFO: Added job "check" to job store "default"
20-Sep-24 21:27:28 INFO: Scheduler started
20-Sep-24 21:27:28 INFO: Start polling
20-Sep-24 21:27:29 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:27:31 INFO: Running job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:34 EEST)" (scheduled at 2024-09-20 21:27:31.965734+03:00)
20-Sep-24 21:27:34 INFO: Job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:34 EEST)" executed successfully
20-Sep-24 21:27:34 INFO: Running job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:37 EEST)" (scheduled at 2024-09-20 21:27:34.965734+03:00)
20-Sep-24 21:27:36 INFO: Job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:37 EEST)" executed successfully
20-Sep-24 21:27:37 INFO: Running job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:40 EEST)" (scheduled at 2024-09-20 21:27:37.965734+03:00)
20-Sep-24 21:27:40 INFO: Job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:40 EEST)" executed successfully
20-Sep-24 21:27:40 INFO: Running job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:43 EEST)" (scheduled at 2024-09-20 21:27:40.965734+03:00)
20-Sep-24 21:27:41 ERROR: Job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:43 EEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 15, in check
    response = requests.get(url[0], timeout=10)  # Таймаут 10 секунд
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
20-Sep-24 21:27:43 INFO: Running job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:46 EEST)" (scheduled at 2024-09-20 21:27:43.965734+03:00)
20-Sep-24 21:27:44 ERROR: Job "check (trigger: interval[0:00:03], next run at: 2024-09-20 21:27:46 EEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 15, in check
    response = requests.get(url[0], timeout=10)  # Таймаут 10 секунд
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
20-Sep-24 21:27:45 INFO: Polling stopped
20-Sep-24 21:27:45 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:27:59 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 21:27:59 INFO: Added job "check" to job store "default"
20-Sep-24 21:27:59 INFO: Scheduler started
20-Sep-24 21:27:59 INFO: Start polling
20-Sep-24 21:27:59 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:28:42 INFO: Polling stopped
20-Sep-24 21:28:42 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:28:47 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 21:28:47 INFO: Added job "check" to job store "default"
20-Sep-24 21:28:47 INFO: Scheduler started
20-Sep-24 21:28:47 INFO: Start polling
20-Sep-24 21:28:47 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:28:57 INFO: Update id=769241950 is handled. Duration 235 ms by bot id=7214056159
20-Sep-24 21:29:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:30:47 EEST)" (scheduled at 2024-09-20 21:29:47.257898+03:00)
20-Sep-24 21:29:49 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:30:47 EEST)" executed successfully
20-Sep-24 21:30:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:31:47 EEST)" (scheduled at 2024-09-20 21:30:47.257898+03:00)
20-Sep-24 21:30:49 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:31:47 EEST)" executed successfully
20-Sep-24 21:31:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:32:47 EEST)" (scheduled at 2024-09-20 21:31:47.257898+03:00)
20-Sep-24 21:31:49 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:32:47 EEST)" executed successfully
20-Sep-24 21:32:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:33:47 EEST)" (scheduled at 2024-09-20 21:32:47.257898+03:00)
20-Sep-24 21:32:49 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:33:47 EEST)" executed successfully
20-Sep-24 21:33:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:34:47 EEST)" (scheduled at 2024-09-20 21:33:47.257898+03:00)
20-Sep-24 21:33:49 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:34:47 EEST)" executed successfully
20-Sep-24 21:34:07 INFO: Update id=769241951 is handled. Duration 141 ms by bot id=7214056159
20-Sep-24 21:34:14 INFO: Update id=769241952 is handled. Duration 203 ms by bot id=7214056159
20-Sep-24 21:34:16 INFO: Update id=769241953 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 21:34:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:35:47 EEST)" (scheduled at 2024-09-20 21:34:47.257898+03:00)
20-Sep-24 21:35:01 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:35:47 EEST)" executed successfully
20-Sep-24 21:35:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:36:47 EEST)" (scheduled at 2024-09-20 21:35:47.257898+03:00)
20-Sep-24 21:35:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:36:47 EEST)" executed successfully
20-Sep-24 21:36:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:37:47 EEST)" (scheduled at 2024-09-20 21:36:47.257898+03:00)
20-Sep-24 21:36:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:37:47 EEST)" executed successfully
20-Sep-24 21:37:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:38:47 EEST)" (scheduled at 2024-09-20 21:37:47.257898+03:00)
20-Sep-24 21:38:00 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:38:47 EEST)" executed successfully
20-Sep-24 21:38:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:39:47 EEST)" (scheduled at 2024-09-20 21:38:47.257898+03:00)
20-Sep-24 21:38:57 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:39:47 EEST)" executed successfully
20-Sep-24 21:39:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:40:47 EEST)" (scheduled at 2024-09-20 21:39:47.257898+03:00)
20-Sep-24 21:39:55 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:40:47 EEST)" executed successfully
20-Sep-24 21:40:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:41:47 EEST)" (scheduled at 2024-09-20 21:40:47.257898+03:00)
20-Sep-24 21:40:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:41:47 EEST)" executed successfully
20-Sep-24 21:41:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:42:47 EEST)" (scheduled at 2024-09-20 21:41:47.257898+03:00)
20-Sep-24 21:41:56 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:42:47 EEST)" executed successfully
20-Sep-24 21:42:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:43:47 EEST)" (scheduled at 2024-09-20 21:42:47.257898+03:00)
20-Sep-24 21:42:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:43:47 EEST)" executed successfully
20-Sep-24 21:43:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:44:47 EEST)" (scheduled at 2024-09-20 21:43:47.257898+03:00)
20-Sep-24 21:43:58 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:44:47 EEST)" executed successfully
20-Sep-24 21:44:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:45:47 EEST)" (scheduled at 2024-09-20 21:44:47.257898+03:00)
20-Sep-24 21:44:58 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:45:47 EEST)" executed successfully
20-Sep-24 21:45:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:46:47 EEST)" (scheduled at 2024-09-20 21:45:47.257898+03:00)
20-Sep-24 21:45:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:46:47 EEST)" executed successfully
20-Sep-24 21:46:47 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:47:47 EEST)" (scheduled at 2024-09-20 21:46:47.257898+03:00)
20-Sep-24 21:46:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:47:47 EEST)" executed successfully
20-Sep-24 21:47:30 INFO: Polling stopped
20-Sep-24 21:47:30 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:56:57 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 21:56:57 INFO: Added job "check" to job store "default"
20-Sep-24 21:56:57 INFO: Scheduler started
20-Sep-24 21:56:57 INFO: Start polling
20-Sep-24 21:56:57 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:57:09 INFO: Update id=769241954 is handled. Duration 218 ms by bot id=7214056159
20-Sep-24 21:57:10 INFO: Update id=769241955 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 21:57:10 ERROR: Cause exception while process update id=769241955 by bot id=7214056159
ValueError: parameters are of unsupported type
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 17, in sdsd
    await check(bot)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 13, in check
    cur.execute("SELECT silent FROM users WHERE uid = ?", (user[0]))
ValueError: parameters are of unsupported type
20-Sep-24 21:57:15 INFO: Polling stopped
20-Sep-24 21:57:15 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:57:26 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 21:57:26 INFO: Added job "check" to job store "default"
20-Sep-24 21:57:26 INFO: Scheduler started
20-Sep-24 21:57:26 INFO: Start polling
20-Sep-24 21:57:26 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 21:57:31 INFO: Update id=769241956 is handled. Duration 3264 ms by bot id=7214056159
20-Sep-24 21:58:26 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:59:26 EEST)" (scheduled at 2024-09-20 21:58:26.223159+03:00)
20-Sep-24 21:58:28 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 21:59:26 EEST)" executed successfully
20-Sep-24 21:59:26 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:00:26 EEST)" (scheduled at 2024-09-20 21:59:26.223159+03:00)
20-Sep-24 21:59:28 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:00:26 EEST)" executed successfully
20-Sep-24 22:00:26 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:01:26 EEST)" (scheduled at 2024-09-20 22:00:26.223159+03:00)
20-Sep-24 22:00:29 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:01:26 EEST)" executed successfully
20-Sep-24 22:00:32 INFO: Polling stopped
20-Sep-24 22:00:32 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:00:40 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:00:40 INFO: Added job "check" to job store "default"
20-Sep-24 22:00:40 INFO: Scheduler started
20-Sep-24 22:00:40 INFO: Start polling
20-Sep-24 22:00:40 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:00:55 INFO: Update id=769241957 is handled. Duration 1577 ms by bot id=7214056159
20-Sep-24 22:01:24 INFO: Update id=769241958 is handled. Duration 1233 ms by bot id=7214056159
20-Sep-24 22:01:40 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:02:40 EEST)" (scheduled at 2024-09-20 22:01:40.113066+03:00)
20-Sep-24 22:01:43 INFO: Update id=769241959 is handled. Duration 4781 ms by bot id=7214056159
20-Sep-24 22:01:43 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:02:40 EEST)" executed successfully
20-Sep-24 22:02:36 INFO: Update id=769241960 is handled. Duration 2313 ms by bot id=7214056159
20-Sep-24 22:02:40 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:03:40 EEST)" (scheduled at 2024-09-20 22:02:40.113066+03:00)
20-Sep-24 22:02:44 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:03:40 EEST)" executed successfully
20-Sep-24 22:03:40 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:04:40 EEST)" (scheduled at 2024-09-20 22:03:40.113066+03:00)
20-Sep-24 22:03:44 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:04:40 EEST)" executed successfully
20-Sep-24 22:03:54 INFO: Polling stopped
20-Sep-24 22:03:54 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:04:00 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:04:00 INFO: Added job "check" to job store "default"
20-Sep-24 22:04:00 INFO: Scheduler started
20-Sep-24 22:04:00 INFO: Start polling
20-Sep-24 22:04:00 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:04:01 INFO: Update id=769241962 is handled. Duration 202 ms by bot id=7214056159
20-Sep-24 22:04:02 INFO: Update id=769241963 is handled. Duration 139 ms by bot id=7214056159
20-Sep-24 22:05:00 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:06:00 EEST)" (scheduled at 2024-09-20 22:05:00.835453+03:00)
20-Sep-24 22:05:04 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:06:00 EEST)" executed successfully
20-Sep-24 22:05:08 INFO: Polling stopped
20-Sep-24 22:05:08 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:13:04 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:13:04 INFO: Added job "check" to job store "default"
20-Sep-24 22:13:04 INFO: Scheduler started
20-Sep-24 22:13:04 INFO: Start polling
20-Sep-24 22:13:04 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:13:08 INFO: Update id=769241964 is handled. Duration 171 ms by bot id=7214056159
20-Sep-24 22:13:11 INFO: Update id=769241965 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 22:13:11 ERROR: Cause exception while process update id=769241965 by bot id=7214056159
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 21, in settings_callback
    kb = settings_kb(call.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\keyboard.py", line 20, in settings_kb
    silent, pause = db.get_setting_user(uid)
TypeError: cannot unpack non-iterable NoneType object
20-Sep-24 22:13:17 INFO: Polling stopped
20-Sep-24 22:13:17 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:13:44 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:13:44 INFO: Added job "check" to job store "default"
20-Sep-24 22:13:44 INFO: Scheduler started
20-Sep-24 22:13:44 INFO: Start polling
20-Sep-24 22:13:44 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:13:46 INFO: Update id=769241966 is not handled. Duration 15 ms by bot id=7214056159
20-Sep-24 22:13:46 ERROR: Cause exception while process update id=769241966 by bot id=7214056159
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 21, in settings_callback
    kb = settings_kb(call.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\keyboard.py", line 20, in settings_kb
    silent, pause = db.get_setting_user(uid)
TypeError: cannot unpack non-iterable NoneType object
20-Sep-24 22:13:50 INFO: Polling stopped
20-Sep-24 22:13:50 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:14:10 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:14:10 INFO: Added job "check" to job store "default"
20-Sep-24 22:14:10 INFO: Scheduler started
20-Sep-24 22:14:10 INFO: Start polling
20-Sep-24 22:14:11 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:14:12 INFO: Update id=769241967 is handled. Duration 202 ms by bot id=7214056159
20-Sep-24 22:14:26 INFO: Update id=769241968 is not handled. Duration 0 ms by bot id=7214056159
20-Sep-24 22:14:27 INFO: Update id=769241969 is handled. Duration 78 ms by bot id=7214056159
20-Sep-24 22:14:28 INFO: Update id=769241970 is handled. Duration 93 ms by bot id=7214056159
20-Sep-24 22:15:10 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:16:10 EEST)" (scheduled at 2024-09-20 22:15:10.989684+03:00)
20-Sep-24 22:15:14 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:16:10 EEST)" executed successfully
20-Sep-24 22:15:15 INFO: Polling stopped
20-Sep-24 22:15:15 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:18:55 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:18:55 INFO: Added job "check" to job store "default"
20-Sep-24 22:18:55 INFO: Scheduler started
20-Sep-24 22:18:55 INFO: Start polling
20-Sep-24 22:18:56 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:18:58 INFO: Update id=769241971 is handled. Duration 186 ms by bot id=7214056159
20-Sep-24 22:18:59 INFO: Update id=769241972 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 22:19:00 INFO: Update id=769241973 is handled. Duration 172 ms by bot id=7214056159
20-Sep-24 22:19:09 INFO: Polling stopped
20-Sep-24 22:19:09 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:19:15 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:19:15 INFO: Added job "check" to job store "default"
20-Sep-24 22:19:15 INFO: Scheduler started
20-Sep-24 22:19:15 INFO: Start polling
20-Sep-24 22:19:15 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:19:16 INFO: Update id=769241974 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 22:19:17 INFO: Update id=769241975 is handled. Duration 47 ms by bot id=7214056159
20-Sep-24 22:19:18 INFO: Update id=769241976 is not handled. Duration 15 ms by bot id=7214056159
20-Sep-24 22:19:18 ERROR: Cause exception while process update id=769241976 by bot id=7214056159
ValidationError: 1 validation error for InlineKeyboardButton
text
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 34, in settings_callback
    kb = settings_kb(call.from_user.id)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\keyboard.py", line 37, in settings_kb
    InlineKeyboardButton(text=pause, callback_data=f"pause_switch")
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for InlineKeyboardButton
text
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
20-Sep-24 22:19:45 INFO: Update id=769241977 is not handled. Duration 172 ms by bot id=7214056159
20-Sep-24 22:19:45 ERROR: Cause exception while process update id=769241977 by bot id=7214056159
TelegramBadRequest: Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\commands.py", line 35, in settings_callback
    await call.message.edit_text("121", reply_markup=kb)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
20-Sep-24 22:19:58 INFO: Polling stopped
20-Sep-24 22:19:58 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:20:03 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:20:03 INFO: Added job "check" to job store "default"
20-Sep-24 22:20:03 INFO: Scheduler started
20-Sep-24 22:20:03 INFO: Start polling
20-Sep-24 22:20:03 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:20:05 INFO: Update id=769241978 is handled. Duration 281 ms by bot id=7214056159
20-Sep-24 22:20:06 INFO: Update id=769241979 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 22:20:07 INFO: Update id=769241980 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:20:08 INFO: Update id=769241981 is handled. Duration 61 ms by bot id=7214056159
20-Sep-24 22:20:09 INFO: Update id=769241982 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:21:03 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:22:03 EEST)" (scheduled at 2024-09-20 22:21:03.761996+03:00)
20-Sep-24 22:21:06 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:22:03 EEST)" executed successfully
20-Sep-24 22:22:03 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:23:03 EEST)" (scheduled at 2024-09-20 22:22:03.761996+03:00)
20-Sep-24 22:22:05 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:23:03 EEST)" executed successfully
20-Sep-24 22:22:50 INFO: Polling stopped
20-Sep-24 22:22:50 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:22:57 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:22:57 INFO: Added job "check" to job store "default"
20-Sep-24 22:22:57 INFO: Scheduler started
20-Sep-24 22:22:57 INFO: Start polling
20-Sep-24 22:22:57 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:22:59 INFO: Update id=769241983 is handled. Duration 186 ms by bot id=7214056159
20-Sep-24 22:23:01 INFO: Update id=769241984 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:23:01 INFO: Update id=769241985 is handled. Duration 78 ms by bot id=7214056159
20-Sep-24 22:23:25 INFO: Update id=769241986 is handled. Duration 155 ms by bot id=7214056159
20-Sep-24 22:23:57 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:24:57 EEST)" (scheduled at 2024-09-20 22:23:57.759792+03:00)
20-Sep-24 22:24:01 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:24:57 EEST)" executed successfully
20-Sep-24 22:24:57 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:25:57 EEST)" (scheduled at 2024-09-20 22:24:57.759792+03:00)
20-Sep-24 22:25:02 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:25:57 EEST)" executed successfully
20-Sep-24 22:25:56 INFO: Update id=769241987 is handled. Duration 218 ms by bot id=7214056159
20-Sep-24 22:25:57 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:26:57 EEST)" (scheduled at 2024-09-20 22:25:57.759792+03:00)
20-Sep-24 22:26:00 INFO: Update id=769241988 is handled. Duration 2140 ms by bot id=7214056159
20-Sep-24 22:26:00 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:26:57 EEST)" executed successfully
20-Sep-24 22:26:00 INFO: Update id=769241989 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 22:26:03 INFO: Update id=769241990 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 22:26:57 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:27:57 EEST)" (scheduled at 2024-09-20 22:26:57.759792+03:00)
20-Sep-24 22:26:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:27:57 EEST)" executed successfully
20-Sep-24 22:27:57 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:28:57 EEST)" (scheduled at 2024-09-20 22:27:57.759792+03:00)
20-Sep-24 22:27:59 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:28:57 EEST)" executed successfully
20-Sep-24 22:27:59 INFO: Polling stopped
20-Sep-24 22:27:59 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:28:05 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:28:05 INFO: Added job "check" to job store "default"
20-Sep-24 22:28:05 INFO: Scheduler started
20-Sep-24 22:28:05 INFO: Start polling
20-Sep-24 22:28:05 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:28:21 INFO: Polling stopped
20-Sep-24 22:28:21 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:28:26 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:28:26 INFO: Added job "check" to job store "default"
20-Sep-24 22:28:26 INFO: Scheduler started
20-Sep-24 22:28:26 INFO: Start polling
20-Sep-24 22:28:26 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:28:27 INFO: Update id=769241992 is handled. Duration 125 ms by bot id=7214056159
20-Sep-24 22:28:28 INFO: Update id=769241993 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:28:31 INFO: Update id=769241994 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:28:32 INFO: Update id=769241995 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:28:33 INFO: Update id=769241996 is handled. Duration 264 ms by bot id=7214056159
20-Sep-24 22:28:34 INFO: Update id=769241997 is handled. Duration 110 ms by bot id=7214056159
20-Sep-24 22:28:35 INFO: Update id=769241998 is handled. Duration 63 ms by bot id=7214056159
20-Sep-24 22:28:36 INFO: Update id=769241999 is handled. Duration 47 ms by bot id=7214056159
20-Sep-24 22:29:26 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:30:26 EEST)" (scheduled at 2024-09-20 22:29:26.523407+03:00)
20-Sep-24 22:29:27 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:30:26 EEST)" executed successfully
20-Sep-24 22:30:23 INFO: Polling stopped
20-Sep-24 22:30:23 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:30:28 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:30:28 INFO: Added job "check" to job store "default"
20-Sep-24 22:30:28 INFO: Scheduler started
20-Sep-24 22:30:28 INFO: Start polling
20-Sep-24 22:30:28 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:30:32 INFO: Update id=769242000 is handled. Duration 218 ms by bot id=7214056159
20-Sep-24 22:30:35 INFO: Update id=769242001 is handled. Duration 93 ms by bot id=7214056159
20-Sep-24 22:31:07 INFO: Update id=769242002 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 22:31:08 INFO: Update id=769242003 is handled. Duration 61 ms by bot id=7214056159
20-Sep-24 22:31:25 INFO: Polling stopped
20-Sep-24 22:31:25 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:31:32 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:31:32 INFO: Added job "check" to job store "default"
20-Sep-24 22:31:32 INFO: Scheduler started
20-Sep-24 22:31:32 INFO: Start polling
20-Sep-24 22:31:32 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:31:33 INFO: Update id=769242005 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 22:31:34 INFO: Update id=769242006 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 22:31:35 INFO: Update id=769242007 is handled. Duration 110 ms by bot id=7214056159
20-Sep-24 22:31:56 INFO: Update id=769242008 is handled. Duration 171 ms by bot id=7214056159
20-Sep-24 22:32:03 INFO: Update id=769242009 is handled. Duration 63 ms by bot id=7214056159
20-Sep-24 22:32:10 INFO: Update id=769242010 is handled. Duration 61 ms by bot id=7214056159
20-Sep-24 22:32:10 INFO: Update id=769242011 is handled. Duration 61 ms by bot id=7214056159
20-Sep-24 22:32:12 INFO: Update id=769242012 is handled. Duration 78 ms by bot id=7214056159
20-Sep-24 22:32:21 INFO: Update id=769242013 is handled. Duration 188 ms by bot id=7214056159
20-Sep-24 22:32:32 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:33:32 EEST)" (scheduled at 2024-09-20 22:32:32.385136+03:00)
20-Sep-24 22:32:43 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:33:32 EEST)" executed successfully
20-Sep-24 22:33:32 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:34:32 EEST)" (scheduled at 2024-09-20 22:33:32.385136+03:00)
20-Sep-24 22:33:39 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:34:32 EEST)" executed successfully
20-Sep-24 22:34:00 INFO: Update id=769242014 is handled. Duration 155 ms by bot id=7214056159
20-Sep-24 22:34:32 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:35:32 EEST)" (scheduled at 2024-09-20 22:34:32.385136+03:00)
20-Sep-24 22:34:42 ERROR: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:35:32 EEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 20, in check
    response = requests.get(url[0], timeout=10)  # Таймаут 10 секунд
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
20-Sep-24 22:34:42 INFO: Polling stopped
20-Sep-24 22:34:42 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:34:54 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:34:54 INFO: Added job "check" to job store "default"
20-Sep-24 22:34:54 INFO: Scheduler started
20-Sep-24 22:34:54 INFO: Start polling
20-Sep-24 22:34:54 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:35:10 INFO: Update id=769242015 is handled. Duration 156 ms by bot id=7214056159
20-Sep-24 22:35:54 INFO: Polling stopped
20-Sep-24 22:35:54 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:35:59 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:35:59 INFO: Added job "check" to job store "default"
20-Sep-24 22:35:59 INFO: Scheduler started
20-Sep-24 22:35:59 INFO: Start polling
20-Sep-24 22:35:59 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:36:13 INFO: Update id=769242016 is handled. Duration 11765 ms by bot id=7214056159
20-Sep-24 22:36:13 INFO: Update id=769242017 is handled. Duration 296 ms by bot id=7214056159
20-Sep-24 22:36:14 INFO: Update id=769242018 is handled. Duration 202 ms by bot id=7214056159
20-Sep-24 22:36:27 INFO: Update id=769242019 is handled. Duration 6921 ms by bot id=7214056159
20-Sep-24 22:36:59 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:37:59 EEST)" (scheduled at 2024-09-20 22:36:59.105279+03:00)
20-Sep-24 22:37:10 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:37:59 EEST)" executed successfully
20-Sep-24 22:37:59 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:38:59 EEST)" (scheduled at 2024-09-20 22:37:59.105279+03:00)
20-Sep-24 22:38:11 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:38:59 EEST)" executed successfully
20-Sep-24 22:38:59 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:39:59 EEST)" (scheduled at 2024-09-20 22:38:59.105279+03:00)
20-Sep-24 22:39:12 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:39:59 EEST)" executed successfully
20-Sep-24 22:39:59 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:40:59 EEST)" (scheduled at 2024-09-20 22:39:59.105279+03:00)
20-Sep-24 22:40:14 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:40:59 EEST)" executed successfully
20-Sep-24 22:40:59 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:41:59 EEST)" (scheduled at 2024-09-20 22:40:59.105279+03:00)
20-Sep-24 22:41:12 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:41:59 EEST)" executed successfully
20-Sep-24 22:41:15 INFO: Polling stopped
20-Sep-24 22:41:15 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:41:20 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:41:20 INFO: Added job "check" to job store "default"
20-Sep-24 22:41:20 INFO: Scheduler started
20-Sep-24 22:41:20 INFO: Start polling
20-Sep-24 22:41:20 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:42:20 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:43:20 EEST)" (scheduled at 2024-09-20 22:42:20.302280+03:00)
20-Sep-24 22:42:32 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:43:20 EEST)" executed successfully
20-Sep-24 22:43:07 INFO: Update id=769242020 is handled. Duration 171 ms by bot id=7214056159
20-Sep-24 22:43:09 INFO: Update id=769242021 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:43:10 INFO: Update id=769242022 is handled. Duration 78 ms by bot id=7214056159
20-Sep-24 22:43:11 INFO: Update id=769242023 is handled. Duration 109 ms by bot id=7214056159
20-Sep-24 22:43:12 INFO: Update id=769242024 is handled. Duration 93 ms by bot id=7214056159
20-Sep-24 22:43:20 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:44:20 EEST)" (scheduled at 2024-09-20 22:43:20.302280+03:00)
20-Sep-24 22:43:34 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:44:20 EEST)" executed successfully
20-Sep-24 22:44:05 INFO: Polling stopped
20-Sep-24 22:44:05 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:44:11 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:44:11 INFO: Added job "check" to job store "default"
20-Sep-24 22:44:11 INFO: Scheduler started
20-Sep-24 22:44:11 INFO: Start polling
20-Sep-24 22:44:11 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:45:11 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:46:11 EEST)" (scheduled at 2024-09-20 22:45:11.386719+03:00)
20-Sep-24 22:45:25 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:46:11 EEST)" executed successfully
20-Sep-24 22:45:25 INFO: Update id=769242025 is handled. Duration 577 ms by bot id=7214056159
20-Sep-24 22:45:25 INFO: Update id=769242026 is handled. Duration 141 ms by bot id=7214056159
20-Sep-24 22:45:56 INFO: Update id=769242027 is handled. Duration 155 ms by bot id=7214056159
20-Sep-24 22:45:58 INFO: Update id=769242028 is handled. Duration 140 ms by bot id=7214056159
20-Sep-24 22:46:11 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:47:11 EEST)" (scheduled at 2024-09-20 22:46:11.386719+03:00)
20-Sep-24 22:46:14 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:47:11 EEST)" executed successfully
20-Sep-24 22:46:19 INFO: Polling stopped
20-Sep-24 22:46:19 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:46:24 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:46:24 INFO: Added job "check" to job store "default"
20-Sep-24 22:46:24 INFO: Scheduler started
20-Sep-24 22:46:24 INFO: Start polling
20-Sep-24 22:46:25 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:46:30 INFO: Update id=769242029 is handled. Duration 2078 ms by bot id=7214056159
20-Sep-24 22:46:38 INFO: Update id=769242030 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 22:46:41 INFO: Update id=769242031 is handled. Duration 125 ms by bot id=7214056159
20-Sep-24 22:46:54 INFO: Update id=769242032 is handled. Duration 12250 ms by bot id=7214056159
20-Sep-24 22:47:24 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:48:24 EEST)" (scheduled at 2024-09-20 22:47:24.309449+03:00)
20-Sep-24 22:47:37 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:48:24 EEST)" executed successfully
20-Sep-24 22:48:24 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:49:24 EEST)" (scheduled at 2024-09-20 22:48:24.309449+03:00)
20-Sep-24 22:48:37 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:49:24 EEST)" executed successfully
20-Sep-24 22:49:24 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:50:24 EEST)" (scheduled at 2024-09-20 22:49:24.309449+03:00)
20-Sep-24 22:49:36 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:50:24 EEST)" executed successfully
20-Sep-24 22:50:24 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:51:24 EEST)" (scheduled at 2024-09-20 22:50:24.309449+03:00)
20-Sep-24 22:50:36 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:51:24 EEST)" executed successfully
20-Sep-24 22:51:00 INFO: Polling stopped
20-Sep-24 22:51:00 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:51:06 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 22:51:06 INFO: Added job "check" to job store "default"
20-Sep-24 22:51:06 INFO: Scheduler started
20-Sep-24 22:51:06 INFO: Start polling
20-Sep-24 22:51:06 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 22:52:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:53:06 EEST)" (scheduled at 2024-09-20 22:52:06.886225+03:00)
20-Sep-24 22:52:19 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:53:06 EEST)" executed successfully
20-Sep-24 22:53:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:54:06 EEST)" (scheduled at 2024-09-20 22:53:06.886225+03:00)
20-Sep-24 22:53:17 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:54:06 EEST)" executed successfully
20-Sep-24 22:54:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:55:06 EEST)" (scheduled at 2024-09-20 22:54:06.886225+03:00)
20-Sep-24 22:54:19 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:55:06 EEST)" executed successfully
20-Sep-24 22:55:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:56:06 EEST)" (scheduled at 2024-09-20 22:55:06.886225+03:00)
20-Sep-24 22:55:16 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:56:06 EEST)" executed successfully
20-Sep-24 22:56:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:57:06 EEST)" (scheduled at 2024-09-20 22:56:06.886225+03:00)
20-Sep-24 22:56:18 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:57:06 EEST)" executed successfully
20-Sep-24 22:57:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:58:06 EEST)" (scheduled at 2024-09-20 22:57:06.886225+03:00)
20-Sep-24 22:57:19 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:58:06 EEST)" executed successfully
20-Sep-24 22:58:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:59:06 EEST)" (scheduled at 2024-09-20 22:58:06.886225+03:00)
20-Sep-24 22:58:17 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 22:59:06 EEST)" executed successfully
20-Sep-24 22:59:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:00:06 EEST)" (scheduled at 2024-09-20 22:59:06.886225+03:00)
20-Sep-24 22:59:15 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:00:06 EEST)" executed successfully
20-Sep-24 23:00:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:01:06 EEST)" (scheduled at 2024-09-20 23:00:06.886225+03:00)
20-Sep-24 23:00:14 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:01:06 EEST)" executed successfully
20-Sep-24 23:01:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:02:06 EEST)" (scheduled at 2024-09-20 23:01:06.886225+03:00)
20-Sep-24 23:01:15 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:02:06 EEST)" executed successfully
20-Sep-24 23:02:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:03:06 EEST)" (scheduled at 2024-09-20 23:02:06.886225+03:00)
20-Sep-24 23:02:31 ERROR: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:03:06 EEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\aiohttp.py", line 171, in make_request
    async with session.post(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 42, in check
    await bot.send_message(chat_id = user[0], text = text, disable_web_page_preview = True, disable_notification=True)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\bot.py", line 2766, in send_message
    return await self(call, request_timeout=request_timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\client\session\aiohttp.py", line 178, in make_request
    raise TelegramNetworkError(method=method, message=f"{type(e).__name__}: {e}")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
20-Sep-24 23:03:06 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:04:06 EEST)" (scheduled at 2024-09-20 23:03:06.886225+03:00)
20-Sep-24 23:03:14 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:04:06 EEST)" executed successfully
20-Sep-24 23:03:16 INFO: Polling stopped
20-Sep-24 23:03:16 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:03:22 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 23:03:22 INFO: Added job "check" to job store "default"
20-Sep-24 23:03:22 INFO: Scheduler started
20-Sep-24 23:03:22 INFO: Start polling
20-Sep-24 23:03:22 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:03:23 INFO: Update id=769242033 is handled. Duration 172 ms by bot id=7214056159
20-Sep-24 23:03:27 INFO: Update id=769242034 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 23:03:29 INFO: Update id=769242035 is handled. Duration 63 ms by bot id=7214056159
20-Sep-24 23:03:34 INFO: Update id=769242036 is not handled. Duration 109 ms by bot id=7214056159
20-Sep-24 23:03:34 ERROR: Cause exception while process update id=769242036 by bot id=7214056159
OperationalError: near "website": syntax error
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\handlers\addsite.py", line 41, in add_site_2step
    db.del_site(msg.from_user.id, msg.text)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\database.py", line 25, in del_site
    cur.execute("DELETE FROM sites WHERE uid = ? website = ?", (uid, site))
sqlite3.OperationalError: near "website": syntax error
20-Sep-24 23:03:35 INFO: Update id=769242037 is handled. Duration 93 ms by bot id=7214056159
20-Sep-24 23:03:45 INFO: Polling stopped
20-Sep-24 23:03:45 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:03:51 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 23:03:51 INFO: Added job "check" to job store "default"
20-Sep-24 23:03:51 INFO: Scheduler started
20-Sep-24 23:03:51 INFO: Start polling
20-Sep-24 23:03:51 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:03:52 INFO: Update id=769242038 is handled. Duration 139 ms by bot id=7214056159
20-Sep-24 23:03:53 INFO: Update id=769242039 is handled. Duration 93 ms by bot id=7214056159
20-Sep-24 23:03:54 INFO: Update id=769242040 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 23:04:07 INFO: Update id=769242041 is handled. Duration 156 ms by bot id=7214056159
20-Sep-24 23:04:08 INFO: Update id=769242042 is handled. Duration 47 ms by bot id=7214056159
20-Sep-24 23:04:10 INFO: Update id=769242043 is handled. Duration 61 ms by bot id=7214056159
20-Sep-24 23:04:15 INFO: Update id=769242044 is handled. Duration 47 ms by bot id=7214056159
20-Sep-24 23:04:51 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:05:51 EEST)" (scheduled at 2024-09-20 23:04:51.206310+03:00)
20-Sep-24 23:05:17 ERROR: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:05:51 EEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "c:\Users\albio\OneDrive\Рабочий стол\Yasya Prokopenko\utils\checksites.py", line 20, in check
    response = requests.get(url[0], timeout=10)  # Таймаут 10 секунд
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\albio\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
20-Sep-24 23:05:17 INFO: Update id=769242045 is handled. Duration 10250 ms by bot id=7214056159
20-Sep-24 23:05:17 INFO: Update id=769242047 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 23:05:17 INFO: Update id=769242046 is handled. Duration 10593 ms by bot id=7214056159
20-Sep-24 23:05:18 INFO: Polling stopped
20-Sep-24 23:05:18 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:05:23 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 23:05:23 INFO: Added job "check" to job store "default"
20-Sep-24 23:05:23 INFO: Scheduler started
20-Sep-24 23:05:23 INFO: Start polling
20-Sep-24 23:05:23 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:05:25 INFO: Update id=769242048 is handled. Duration 156 ms by bot id=7214056159
20-Sep-24 23:05:37 INFO: Update id=769242049 is handled. Duration 77 ms by bot id=7214056159
20-Sep-24 23:05:38 INFO: Update id=769242050 is handled. Duration 94 ms by bot id=7214056159
20-Sep-24 23:05:56 INFO: Update id=769242052 is handled. Duration 1311 ms by bot id=7214056159
20-Sep-24 23:05:56 INFO: Update id=769242051 is handled. Duration 16375 ms by bot id=7214056159
20-Sep-24 23:06:23 INFO: Running job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:07:23 EEST)" (scheduled at 2024-09-20 23:06:23.263536+03:00)
20-Sep-24 23:06:34 INFO: Job "check (trigger: interval[0:01:00], next run at: 2024-09-20 23:07:23 EEST)" executed successfully
20-Sep-24 23:06:36 INFO: Update id=769242053 is handled. Duration 7125 ms by bot id=7214056159
20-Sep-24 23:07:00 INFO: Polling stopped
20-Sep-24 23:07:00 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:07:30 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 23:07:30 INFO: Added job "check" to job store "default"
20-Sep-24 23:07:30 INFO: Scheduler started
20-Sep-24 23:07:30 INFO: Start polling
20-Sep-24 23:07:30 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:07:38 INFO: Update id=769242055 is handled. Duration 172 ms by bot id=7214056159
20-Sep-24 23:07:40 INFO: Update id=769242056 is handled. Duration 203 ms by bot id=7214056159
20-Sep-24 23:07:41 INFO: Update id=769242057 is handled. Duration 171 ms by bot id=7214056159
20-Sep-24 23:07:43 INFO: Update id=769242058 is handled. Duration 156 ms by bot id=7214056159
20-Sep-24 23:07:58 INFO: Polling stopped
20-Sep-24 23:07:58 INFO: Polling stopped for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:08:03 INFO: Adding job tentatively -- it will be properly scheduled when the scheduler starts
20-Sep-24 23:08:03 INFO: Added job "check" to job store "default"
20-Sep-24 23:08:03 INFO: Scheduler started
20-Sep-24 23:08:03 INFO: Start polling
20-Sep-24 23:08:03 INFO: Run polling for bot @lopez1k_codebot id=7214056159 - 'Code Bot'
20-Sep-24 23:38:03 INFO: Running job "check (trigger: interval[0:30:00], next run at: 2024-09-21 00:08:03 EEST)" (scheduled at 2024-09-20 23:38:03.853806+03:00)
20-Sep-24 23:38:13 INFO: Job "check (trigger: interval[0:30:00], next run at: 2024-09-21 00:08:03 EEST)" executed successfully
21-Sep-24 00:08:03 INFO: Running job "check (trigger: interval[0:30:00], next run at: 2024-09-21 00:38:03 EEST)" (scheduled at 2024-09-21 00:08:03.853806+03:00)
21-Sep-24 00:08:12 INFO: Job "check (trigger: interval[0:30:00], next run at: 2024-09-21 00:38:03 EEST)" executed successfully
